### PR TITLE
Proper Pubsub support

### PR DESCRIPTION
**Pull request by keks**
Recently I put a lot of effort into making things smooth on the server side. Here is the API code, that ignores the first packet sent because it is only used to force a flush.

Maybe the pubsub test should not be run if the server is not started with pubsub enabled? Don't know how to check that though.

### CODE REVIEW

**Comment by keks** [comment]
Yeah, that's what I thought. We need to run the daemon with the pubsub experiment enabled.

**Comment by keks** [comment]
CR pls @Kubuxu @whyrusleeping @lgierth

**Comment by whyrusleeping** [comment]
This LGTM, thanks @keks !

**Comment by hsanjuan** [comment]
Too late, but tests are not passing for this one. Forgot to add new dependencies to Gx....

**Comment by keks** [comment]
Oh, how could that happen? What did I miss and why did it build now?

**Comment by keks** [comment]
I mean there aren't any dependencies in package.json. We could have bumped the version, though.

**Comment by keks** [comment]
Fix by retry.

**Pull request merged**
