### PR TITLE
Update go-ipfs-files to 2.0

### PR DESCRIPTION
**Pull request by magik6k**
Depends on https://github.com/ipfs/go-ipfs-files/pull/2

### CODE REVIEW

**Comment by magik6k** [comment]
(Tests pass for me locally, and they should start passing once this and go-ipfs-files refactor are merged)

**Comment by magik6k** [comment]
It doesn't pass because ci isn't using gx here

**Comment by Stebalien** [comment]
Ah... Got it.

**Comment by magik6k** [comment]
(tests pass for me locally)

**Comment by Stebalien** [comment]
Fair point. I thought there was a reason we *couldn't* use gx but I should have investigated this more.

**Pull request merged**
