### PR TITLE
fix list commands

### PR DESCRIPTION
**Pull request by whyrusleeping**
@cryptix does this fix your issues?

### CODE REVIEW

**Comment by cryptix** [comment]
@whyrusleeping I tried rebasing this on #14 - `List()` works but now I get json errors for `FileList()`?

`shell_test.go:71: json: cannot unmarshal string into Go value of type int`

diff to 14:
```diff
diff --git a/shell_test.go b/shell_test.go
index 90b8a91..4668d0c 100644
--- a/shell_test.go
+++ b/shell_test.go
@@ -48,12 +48,12 @@ func TestList(t *testing.T) {
 
 	// TODO: document difference in sice betwen 'ipfs ls' and 'ipfs file ls -v'. additional object encoding in data block?
 	expected := map[string]LsLink{
-		"about":          {Type: "File", Hash: "QmZTR5bcpQD7cFgTorqxZDYaew1Wqgfbd2ud9QqGPAkK2V", Name: "about", Size: 1677},
-		"contact":        {Type: "File", Hash: "QmYCvbfNbCwFR45HiNP45rwJgvatpiW38D961L5qAhUM5Y", Name: "contact", Size: 189},
-		"help":           {Type: "File", Hash: "QmY5heUM5qgRubMDD1og9fhCPA6QdkMp3QCwd4s7gJsyE7", Name: "help", Size: 311},
-		"quick-start":    {Type: "File", Hash: "QmUzLxaXnM8RYCPEqLDX5foToi5aNZHqfYr285w2BKhkft", Name: "quick-start", Size: 1686},
-		"readme":         {Type: "File", Hash: "QmPZ9gcCEpqKTo6aq61g2nXGUhM4iCL3ewB6LDXZCtioEB", Name: "readme", Size: 1091},
-		"security-notes": {Type: "File", Hash: "QmTumTjvcYCAvRRwQ8sDRxh8ezmrcr88YFU7iYNroGGTBZ", Name: "security-notes", Size: 1016},
+		"about":          {Type: 2, Hash: "QmZTR5bcpQD7cFgTorqxZDYaew1Wqgfbd2ud9QqGPAkK2V", Name: "about", Size: 1688},
+		"contact":        {Type: 2, Hash: "QmYCvbfNbCwFR45HiNP45rwJgvatpiW38D961L5qAhUM5Y", Name: "contact", Size: 200},
+		"help":           {Type: 2, Hash: "QmY5heUM5qgRubMDD1og9fhCPA6QdkMp3QCwd4s7gJsyE7", Name: "help", Size: 322},
+		"quick-start":    {Type: 2, Hash: "QmUzLxaXnM8RYCPEqLDX5foToi5aNZHqfYr285w2BKhkft", Name: "quick-start", Size: 1697},
+		"readme":         {Type: 2, Hash: "QmPZ9gcCEpqKTo6aq61g2nXGUhM4iCL3ewB6LDXZCtioEB", Name: "readme", Size: 1102},
+		"security-notes": {Type: 2, Hash: "QmTumTjvcYCAvRRwQ8sDRxh8ezmrcr88YFU7iYNroGGTBZ", Name: "security-notes", Size: 1027},
 	}
 	for _, l := range list {
 		el, ok := expected[l.Name]
@@ -75,13 +75,13 @@ func TestFileList(t *testing.T) {
 	is.Equal(len(list.Links), 6)
 
 	// TODO: document difference in sice betwen 'ipfs ls' and 'ipfs file ls -v'. additional object encoding in data block?
-	expected := map[string]LsLink{
-		"about":          {Type: "File", Hash: "QmZTR5bcpQD7cFgTorqxZDYaew1Wqgfbd2ud9QqGPAkK2V", Name: "about", Size: 1677},
-		"contact":        {Type: "File", Hash: "QmYCvbfNbCwFR45HiNP45rwJgvatpiW38D961L5qAhUM5Y", Name: "contact", Size: 189},
-		"help":           {Type: "File", Hash: "QmY5heUM5qgRubMDD1og9fhCPA6QdkMp3QCwd4s7gJsyE7", Name: "help", Size: 311},
-		"quick-start":    {Type: "File", Hash: "QmUzLxaXnM8RYCPEqLDX5foToi5aNZHqfYr285w2BKhkft", Name: "quick-start", Size: 1686},
-		"readme":         {Type: "File", Hash: "QmPZ9gcCEpqKTo6aq61g2nXGUhM4iCL3ewB6LDXZCtioEB", Name: "readme", Size: 1091},
-		"security-notes": {Type: "File", Hash: "QmTumTjvcYCAvRRwQ8sDRxh8ezmrcr88YFU7iYNroGGTBZ", Name: "security-notes", Size: 1016},
+	expected := map[string]UnixLsObject{
+		"about":          {Type: "File", Hash: "QmZTR5bcpQD7cFgTorqxZDYaew1Wqgfbd2ud9QqGPAkK2V", Size: 1677},
+		"contact":        {Type: "File", Hash: "QmYCvbfNbCwFR45HiNP45rwJgvatpiW38D961L5qAhUM5Y", Size: 189},
+		"help":           {Type: "File", Hash: "QmY5heUM5qgRubMDD1og9fhCPA6QdkMp3QCwd4s7gJsyE7", Size: 311},
+		"quick-start":    {Type: "File", Hash: "QmUzLxaXnM8RYCPEqLDX5foToi5aNZHqfYr285w2BKhkft", Size: 1686},
+		"readme":         {Type: "File", Hash: "QmPZ9gcCEpqKTo6aq61g2nXGUhM4iCL3ewB6LDXZCtioEB", Size: 1091},
+		"security-notes": {Type: "File", Hash: "QmTumTjvcYCAvRRwQ8sDRxh8ezmrcr88YFU7iYNroGGTBZ", Size: 1016},
 	}
 	for _, l := range list.Links {
 		el, ok := expected[l.Name]
```

**Comment by whyrusleeping** [comment]
I'm not a fan of how this testing library prints errors:
```
shell_test.go:74: expected nil: &json.UnmarshalTypeError{Value:"string", Type:(*reflect.rtype)(0x6ca260), Offset:482}
```

When it really means:

```
shell_test.go:75: json: cannot unmarshal string into Go value of type int
```

**Comment by whyrusleeping** [comment]
@cryptix updated this branch to work more betterer. it should be fine to rebase yours on top of (although you'll have to change some types in your test)

**Comment by jbenet** [comment]
LGTM

**Comment by jbenet** [comment]
@whyrusleeping MR?

**Comment by whyrusleeping** [comment]
MR?

**Comment by jbenet** [comment]
Merge Ready?

**Comment by whyrusleeping** [comment]
yeap, i think so.

**Pull request merged**
